version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_URL=${CELERY_RESULT_URL}
    command: ["celery", "-A", "helpers.celery_tasks.celery_worker.celery_app", "worker", "--loglevel=info"]

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
